/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Service.Impl.QLChiTietSPServiceImpl;
import Service.Impl.QLDongSPServiceImpl;
import Service.Impl.QLMauSacServiceImpl;
import Service.Impl.QLNSXServiceImpl;
import Service.Impl.QLSanPhamServiceImpl;
import Service.QLChiTietSPService;
import Service.QLDongSPService;
import Service.QLMauSacService;
import Service.QLNSXService;
import Service.QLSanPhamService;
import ViewModels.QLChiTietSP;
import ViewModels.QLDongSP;
import ViewModels.QLMauSac;
import ViewModels.QLNSX;
import ViewModels.QLSanPham;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FrmChiTietSP extends javax.swing.JFrame {

    private List<QLChiTietSP> listQLChiTietSP = new ArrayList<>();
    private List<QLSanPham> listQLSP = new ArrayList<>();
    private List<QLNSX> listQLNSX = new ArrayList<>();
    private List<QLMauSac> listQLMS = new ArrayList<>();
    private List<QLDongSP> listQLDongSP = new ArrayList<>();
    private DefaultTableModel dtm;
    private QLChiTietSPService qlctsps = new QLChiTietSPServiceImpl();
    private QLSanPhamService qlsps = new QLSanPhamServiceImpl();
    private QLNSXService qlnsxs = new QLNSXServiceImpl();
    private QLDongSPService qldsps = new QLDongSPServiceImpl();
    private QLMauSacService qlmss = new QLMauSacServiceImpl();

    /**
     * Creates new form FrmChiTietSP
     */
    public FrmChiTietSP() {
        initComponents();
        jTable1.setModel(dtm = new DefaultTableModel());
        String[] header = {"ID", "SP", "NSX", "Mau Sac", "Dong SP", "Nam BH", "Mo Ta", "So Luong Ton", "Gia Nhap", "Gia Ban"};
        dtm.setColumnIdentifiers(header);
        listQLChiTietSP = qlctsps.getAll();
        listQLDongSP = qldsps.getAll();
        listQLMS = qlmss.getAll();
        listQLNSX = qlnsxs.getAll();
        listQLSP = qlsps.getAll();
        loadCbbSP();
        loadCbbDongSP();
        loadCbbMS();
        loadCbbNSX();
        showData(listQLChiTietSP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbSanPham = new javax.swing.JComboBox<>();
        cbbNSX = new javax.swing.JComboBox<>();
        cbbMauSac = new javax.swing.JComboBox<>();
        cbbDongSP = new javax.swing.JComboBox<>();
        txtNamBH = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtSoLuongTon = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Chi Tiet SP");

        jLabel2.setText("San Pham");

        jLabel3.setText("NSX");

        jLabel4.setText("Dong SP");

        jLabel5.setText("Mau Sac");

        jLabel6.setText("Nam BH");

        jLabel7.setText("Mo Ta");

        jLabel8.setText("So Luong Ton");

        jLabel9.setText("Gia Nhap");

        jLabel10.setText("Gia Ban");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(btnXoa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(82, 82, 82)
                                .addComponent(btnSua))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbDongSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    private void showData(List<QLChiTietSP> listQLChiTietSP) {
        dtm.setRowCount(0);
        for (QLChiTietSP qLChiTietSP : listQLChiTietSP) {
            dtm.addRow(qLChiTietSP.toDataRow());
        }
    }

    private void fillData(int index) {
        QLChiTietSP x = listQLChiTietSP.get(index);
        txtGiaBan.setText(String.valueOf(x.getGiaBan()));
        txtGiaNhap.setText(String.valueOf(x.getGiaNhap()));
        txtMoTa.setText(x.getMoTa());
        txtNamBH.setText(String.valueOf(x.getNamBH()));
        txtSoLuongTon.setText(String.valueOf(x.getSoLuongTon()));
        cbbDongSP.setSelectedItem(x.getIdDongSP().getTen());
        cbbMauSac.setSelectedItem(x.getIdMauSac().getTen());
        cbbNSX.setSelectedItem(x.getIdNSX().getTen());
        cbbSanPham.setSelectedItem(x.getIdSP().getTen());
    }

    private void insert() {
        String namBH = txtNamBH.getText().trim();
        String moTa = txtMoTa.getText().trim();
        String giaNhap = txtGiaNhap.getText().trim();
        String giaBan = txtGiaBan.getText().trim();
        String soLuongTon = txtSoLuongTon.getText().trim();
        if (namBH.length() == 0 || moTa.length() == 0 || giaNhap.length() == 0 || giaBan.length() == 0 || soLuongTon.length() == 0) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong");
        } else {
            QLNSX idNSX = new QLNSX(getNSX());
            QLDongSP idDongSP = new QLDongSP(getDongSP());
            QLMauSac idMS = new QLMauSac(getMS());
            QLSanPham idSP = new QLSanPham(getSP());
            QLChiTietSP qlctsp = new QLChiTietSP(idSP, idNSX, idMS, idDongSP, Integer.valueOf(namBH), moTa, Integer.valueOf(soLuongTon), Double.valueOf(giaNhap), Double.valueOf(giaBan));
            JOptionPane.showMessageDialog(this, qlctsps.insert(qlctsp));
            listQLChiTietSP = qlctsps.getAll();
            showData(listQLChiTietSP);
        }

    }

    private void update() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            QLChiTietSP p = listQLChiTietSP.get(row);
            UUID id = p.getId();
            String namBH = txtNamBH.getText().trim();
            String moTa = txtMoTa.getText().trim();
            String giaNhap = txtGiaNhap.getText().trim();
            String giaBan = txtGiaBan.getText().trim();
            String soLuongTon = txtSoLuongTon.getText().trim();
            if (namBH.length() == 0 || moTa.length() == 0 || giaNhap.length() == 0 || giaBan.length() == 0 || soLuongTon.length() == 0) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } else {
                QLNSX idNSX = new QLNSX(getNSX());
                QLDongSP idDongSP = new QLDongSP(getDongSP());
                QLMauSac idMS = new QLMauSac(getMS());
                QLSanPham idSP = new QLSanPham(getSP());
                QLChiTietSP qlctsp = new QLChiTietSP(idSP, idNSX, idMS, idDongSP, Integer.valueOf(namBH), moTa, Integer.valueOf(soLuongTon), Double.valueOf(giaNhap), Double.valueOf(giaBan));
                JOptionPane.showMessageDialog(this, qlctsps.update(qlctsp, id));
                listQLChiTietSP = qlctsps.getAll();
                showData(listQLChiTietSP);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Moi chon doi tuong de sua");
        }
    }

    private void delete() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            QLChiTietSP p = listQLChiTietSP.get(row);
            UUID id = p.getId();
            JOptionPane.showMessageDialog(this, qlctsps.delete(id));
            listQLChiTietSP = qlctsps.getAll();
            showData(listQLChiTietSP);
        } else {
            JOptionPane.showMessageDialog(this, "Moi chon doi tuong de xoa");
        }
    }

    private void loadCbbSP() {
        for (QLSanPham qLSanPham : listQLSP) {
            cbbSanPham.addItem(qLSanPham.getTen());
        }
    }

    private void loadCbbMS() {
        for (QLMauSac qLMauSac : listQLMS) {
            cbbMauSac.addItem(qLMauSac.getTen());
        }
    }

    private void loadCbbNSX() {
        for (QLNSX qlnsx : listQLNSX) {
            cbbNSX.addItem(qlnsx.getTen());
        }
    }

    private void loadCbbDongSP() {
        for (QLDongSP qLDongSP : listQLDongSP) {
            cbbDongSP.addItem(qLDongSP.getTen());
        }
    }

    private UUID getSP() {
        String sanPham = (String) cbbSanPham.getSelectedItem();
        UUID idSP = null;
        for (QLSanPham qLSanPham : listQLSP) {
            if (qLSanPham.getTen().equals(sanPham)) {
                idSP = qLSanPham.getId();
            }
        }
        return idSP;
    }

    private UUID getNSX() {
        String nsx = (String) cbbNSX.getSelectedItem();
        UUID idNSX = null;
        for (QLNSX qlnsx : listQLNSX) {
            if (qlnsx.getTen().equals(nsx)) {
                idNSX = qlnsx.getId();
            }
        }

        return idNSX;
    }

    private UUID getMS() {
        String mauSac = (String) cbbMauSac.getSelectedItem();
        UUID idMS = null;
        for (QLMauSac qLMauSac : listQLMS) {
            if (qLMauSac.getTen().equals(mauSac)) {
                idMS = qLMauSac.getId();
            }
        }
        return idMS;
    }

    private UUID getDongSP() {
        String dongSp = (String) cbbDongSP.getSelectedItem();
        UUID idDongSP = null;
        for (QLDongSP qLDongSP : listQLDongSP) {
            if (qLDongSP.getTen().equals(dongSp)) {
                idDongSP = qLDongSP.getId();
            }
        }
        return idDongSP;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChiTietSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDongSP;
    private javax.swing.JComboBox<String> cbbMauSac;
    private javax.swing.JComboBox<String> cbbNSX;
    private javax.swing.JComboBox<String> cbbSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtNamBH;
    private javax.swing.JTextField txtSoLuongTon;
    // End of variables declaration//GEN-END:variables
}
