/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Service.Impl.QLChiTietSPServiceImpl;
import Service.Impl.QLGioHangChiTietServiceImpl;
import Service.Impl.QLGioHangServiceImpl;
import Service.QLChiTietSPService;
import Service.QLGioHangChiTietService;
import Service.QLGioHangService;
import ViewModels.QLChiTietSP;
import ViewModels.QLGioHang;
import ViewModels.QLGioHangChiTiet;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FrmGioHangChiTiet extends javax.swing.JFrame {
    
    private List<QLGioHangChiTiet> listQLGioHangCT = new ArrayList<>();
    private List<QLGioHang> listGioHang = new ArrayList<>();
    private List<QLChiTietSP> listQLChiTietSP = new ArrayList<>();
    private QLChiTietSPService qlctsps = new QLChiTietSPServiceImpl();
    private QLGioHangChiTietService qlghcts = new QLGioHangChiTietServiceImpl();
    private QLGioHangService qlghs = new QLGioHangServiceImpl();
    private DefaultTableModel dtm;

    /**
     * Creates new form FrmGioHangChiTiet
     */
    public FrmGioHangChiTiet() {
        initComponents();
        jTable1.setModel(dtm = new DefaultTableModel());
        String[] header = {"Gio Hang", "Chi Tiet SP", "So Luong", "Don Gia", "Don Gia Khi Giam"};
        dtm.setColumnIdentifiers(header);
        listGioHang = qlghs.getAll();
        listQLChiTietSP = qlctsps.getAll();
        listQLGioHangCT = qlghcts.getAll();
        loadCbbGH();
        loadCbbCTSP();
        showData(listQLGioHangCT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDonGiaKhiGiam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbbGioHang = new javax.swing.JComboBox<>();
        cbbChiTietSP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel2.setText("Gio Hang");

        jLabel3.setText("Chi Tiet San Pham");

        jLabel4.setText("So Luong");

        jLabel5.setText("Don Gia");

        jLabel6.setText("Don Gia Khi Giam");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gio Hang Chi Tiet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtDonGiaKhiGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbGioHang, 0, 119, Short.MAX_VALUE)
                                    .addComponent(cbbChiTietSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(58, 58, 58)
                .addComponent(btnSua)
                .addGap(83, 83, 83)
                .addComponent(btnXoa)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbChiTietSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDonGiaKhiGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed
    
    private void showData(List<QLGioHangChiTiet> listQLGioHang) {
        dtm.setRowCount(0);
        for (QLGioHangChiTiet qlgioHangChiTiet : listQLGioHang) {
            dtm.addRow(qlgioHangChiTiet.toDataRow());
        }
    }
    
    private void fillData(int index) {
        QLGioHangChiTiet qlghct = listQLGioHangCT.get(index);
        txtDonGia.setText(String.valueOf(qlghct.getDonGia()));
        txtDonGiaKhiGiam.setText(String.valueOf(qlghct.getDonGiaKhiGiam()));
        txtSoLuong.setText(String.valueOf(qlghct.getSoLuong()));
        cbbChiTietSP.setSelectedItem(qlghct.getIdChiTietSP().getId());
        cbbGioHang.setSelectedItem(qlghct.getIdGioHang().getId());
    }
    
    private void loadCbbGH() {
        for (QLGioHang qLGioHang : listGioHang) {
            cbbGioHang.addItem(String.valueOf(qLGioHang.getIdKH().getTen()));
        }
    }
    
    private void loadCbbCTSP() {
        for (QLChiTietSP qLChiTietSP : listQLChiTietSP) {
            cbbChiTietSP.addItem(String.valueOf(qLChiTietSP.getIdSP().getTen()));
        }
    }
    
    private UUID getGioHang() {
        String gioHang = (String) cbbGioHang.getSelectedItem();
        UUID idGH = null;
        for (QLGioHang qLGioHang : listGioHang) {
            if (qLGioHang.getIdKH().getTen().equals(gioHang)) {
                idGH = qLGioHang.getId();
            }
        }
        return idGH;
    }
    
    private UUID getCTSP() {
        String chiTiet = (String) cbbChiTietSP.getSelectedItem();
        UUID idCTSP = null;
        for (QLChiTietSP qLChiTietSP : listQLChiTietSP) {
            if (qLChiTietSP.getIdSP().getTen().equals(chiTiet)) {
                idCTSP = qLChiTietSP.getId();
            }
        }
        return idCTSP;
    }
    
    private void insert() {
        String soLuong = txtSoLuong.getText().trim();
        String donGia = txtDonGia.getText().trim();
        String donGiaKhiGiam = txtDonGiaKhiGiam.getText().trim();
        
        if (soLuong.length() == 0 || donGia.length() == 0 || donGiaKhiGiam.length() == 0) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong");
        } else {
            QLGioHang idGH = new QLGioHang(getGioHang());
            QLChiTietSP idCTSP = new QLChiTietSP(getCTSP());
            QLGioHangChiTiet qlghct = new QLGioHangChiTiet(idGH, idCTSP, Integer.valueOf(soLuong), Double.valueOf(donGia), Double.valueOf(donGiaKhiGiam));
            JOptionPane.showMessageDialog(this, qlghcts.insert(qlghct));
            listQLGioHangCT = qlghcts.getAll();
            showData(listQLGioHangCT);
        }
    }
    
    private void update() {
        String soLuong = txtSoLuong.getText().trim();
        String donGia = txtDonGia.getText().trim();
        String donGiaKhiGiam = txtDonGiaKhiGiam.getText().trim();
        int row = jTable1.getSelectedRow();
        QLGioHangChiTiet qlghct1 = listQLGioHangCT.get(row);
        UUID id = qlghct1.getIdGioHang().getId();
        if (row >= 0) {
            if (soLuong.length() == 0 || donGia.length() == 0 || donGiaKhiGiam.length() == 0) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } else {
                QLGioHang idGH = new QLGioHang(getGioHang());
                QLChiTietSP idCTSP = new QLChiTietSP(getCTSP());
                QLGioHangChiTiet qlghct = new QLGioHangChiTiet(idGH, idCTSP, Integer.valueOf(soLuong), Double.valueOf(donGia), Double.valueOf(donGiaKhiGiam));
                JOptionPane.showMessageDialog(this, qlghcts.update(qlghct, id));
                listQLGioHangCT = qlghcts.getAll();
                showData(listQLGioHangCT);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon doi tuong xoa");
        }
    }
    
    private void delete() {
        int row = jTable1.getSelectedRow();
        QLGioHangChiTiet qlghct = listQLGioHangCT.get(row);
        UUID id = qlghct.getIdGioHang().getId();
        if (row >= 0) {
            JOptionPane.showMessageDialog(this, qlghcts.delete(id));
            listQLGioHangCT = qlghcts.getAll();
            showData(listQLGioHangCT);
            
        } else {
            JOptionPane.showMessageDialog(this, "Chon doi tuong xoa");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGioHangChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGioHangChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGioHangChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGioHangChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGioHangChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChiTietSP;
    private javax.swing.JComboBox<String> cbbGioHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonGiaKhiGiam;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
