/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Service.Impl.QLChiTietSPServiceImpl;
import Service.Impl.QLHoaDonChiTietServiceImpl;
import Service.Impl.QLHoaDonServiceImpl;
import Service.QLChiTietSPService;
import Service.QLHoaDonChiTietService;
import Service.QLHoaDonService;
import ViewModels.QLChiTietSP;
import ViewModels.QLHoaDon;
import ViewModels.QLHoaDonChiTiet;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FrmHoaDonChiTiet extends javax.swing.JFrame {

    private List<QLHoaDonChiTiet> listQLHDCT = new ArrayList<>();
    private List<QLHoaDon> listHoaDon = new ArrayList<>();
    private List<QLChiTietSP> listCTSP = new ArrayList<>();
    private QLHoaDonChiTietService qlhdcts = new QLHoaDonChiTietServiceImpl();
    private QLHoaDonService qlhds = new QLHoaDonServiceImpl();
    private QLChiTietSPService qlctsp = new QLChiTietSPServiceImpl();
    private DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form FrmHoaDonChiTiet
     */
    public FrmHoaDonChiTiet() {
        initComponents();
        jTable1.setModel(dtm);
        String[] header = {"Hoa Don", "Chi Tiet SP", "So Luong", "Don Gia"};
        dtm.setColumnIdentifiers(header);
        listCTSP = qlctsp.getAll();
        listHoaDon = qlhds.getAll();
        listQLHDCT = qlhdcts.getAll();
        loadCbbCTSP();
        loadCbbHD();
        showData(listQLHDCT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        cbbHoaDon = new javax.swing.JComboBox<>();
        cbbChiTietSP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Hoa Don Chi Tiet");

        jLabel2.setText("Hoa Don");

        jLabel3.setText("Chi Tiet San Pham");

        jLabel4.setText("So Luong");

        jLabel5.setText("Don Gia");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnThem)
                        .addGap(58, 58, 58)
                        .addComponent(btnSua))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbChiTietSP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(56, 56, 56)
                                .addComponent(cbbHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbbHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbChiTietSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_jTable1MouseClicked

    private void showData(List<QLHoaDonChiTiet> listHDCT) {
        dtm.setRowCount(0);
        for (QLHoaDonChiTiet qLHoaDonChiTiet : listHDCT) {
            dtm.addRow(qLHoaDonChiTiet.toDataRow());
        }
    }

    private void fillData(int index){
        QLHoaDonChiTiet qlhdct = listQLHDCT.get(index);
        txtDonGia.setText(String.valueOf(qlhdct.getDonGia()));
        txtSoLuong.setText(String.valueOf(qlhdct.getSoLuong()));
        cbbChiTietSP.setSelectedItem(qlhdct.getIdChiTietSP().getIdSP());
        cbbHoaDon.setSelectedItem(qlhdct.getIdHoaDon().getIdKH());
    }
    private void loadCbbHD() {
        for (QLHoaDon qLHoaDon : listHoaDon) {
            cbbHoaDon.addItem(qLHoaDon.getIdKH().getTen());
        }
    }

    private void loadCbbCTSP() {
        for (QLChiTietSP qLChiTietSP : listCTSP) {
            cbbChiTietSP.addItem(qLChiTietSP.getIdSP().getTen());
        }
    }

    private UUID getIdHoaDon() {
        String hoaDon = (String) cbbHoaDon.getSelectedItem();
        UUID idHD = null;
        for (QLHoaDon qLHoaDon : listHoaDon) {
            if (qLHoaDon.getIdKH().getTen().equals(hoaDon)) {
                idHD = qLHoaDon.getId();
            }
        }
        return idHD;
    }

    private UUID getIdCTSP() {
        String chiTietSP = (String) cbbChiTietSP.getSelectedItem();
        UUID idCTSP = null;
        for (QLChiTietSP qLChiTietSP : listCTSP) {
            if (qLChiTietSP.getIdSP().getTen().equals(chiTietSP)) {
                idCTSP = qLChiTietSP.getId();
            }
        }
        return idCTSP;
    }

    private void insert() {
        String soLuong = txtSoLuong.getText().trim();
        String donGia = txtDonGia.getText().trim();
        QLHoaDon idHD = new QLHoaDon(getIdHoaDon());
        QLChiTietSP idCTSP = new QLChiTietSP(getIdCTSP());
        if (soLuong.length() == 0 || donGia.length() == 0) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong");
        } else {
            QLHoaDonChiTiet qlhdct = new QLHoaDonChiTiet(idHD, idCTSP, Integer.valueOf(soLuong), Double.valueOf(donGia));
            JOptionPane.showMessageDialog(this, qlhdcts.insert(qlhdct));
            listQLHDCT = qlhdcts.getAll();
            showData(listQLHDCT);
        }
    }

    private void delete() {
        int row = jTable1.getSelectedRow();
        QLHoaDonChiTiet qlhdct1 = listQLHDCT.get(row);
        UUID id = qlhdct1.getIdHoaDon().getId();
        if (row >= 0) {
            JOptionPane.showMessageDialog(this, qlhdcts.delete(id));
            listQLHDCT = qlhdcts.getAll();
            showData(listQLHDCT);
        } else {
            JOptionPane.showMessageDialog(this, "Chon doi tuong xoa");
        }
    }

    private void update() {
        int row = jTable1.getSelectedRow();
        QLHoaDonChiTiet qlhdct1 = listQLHDCT.get(row);
        UUID id = qlhdct1.getIdHoaDon().getId();
        if (row >= 0) {
            String soLuong = txtSoLuong.getText().trim();
            String donGia = txtDonGia.getText().trim();
            QLHoaDon idHD = new QLHoaDon(getIdHoaDon());
            QLChiTietSP idCTSP = new QLChiTietSP(getIdCTSP());
            if (soLuong.length() == 0 || donGia.length() == 0) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong");
            } else {
                QLHoaDonChiTiet qlhdct = new QLHoaDonChiTiet(idHD, idCTSP, Integer.valueOf(soLuong), Double.valueOf(donGia));
                JOptionPane.showMessageDialog(this, qlhdcts.update(qlhdct, id));
                listQLHDCT = qlhdcts.getAll();
                showData(listQLHDCT);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon doi tuong sua");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHoaDonChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHoaDonChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChiTietSP;
    private javax.swing.JComboBox<String> cbbHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

}
